name: InventorySystem

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: check-code
        uses: actions/checkout@main
      - name: java
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: build
        run: mvn clean install
      - name: login-to-docker
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: docker build
        run: docker build -t kdale119/inventory-system .
      - name: docker publish
        run: docker push kdale119/inventory-system:latest