name: InventorySystem

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: check-code
        uses: actions/checkout@main
      - name: java
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: build
        run: mvn clean install