name: InventorySystem

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: check-code
        uses: actions/checkout@main
      - name: java
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: build
        run: mvn clean install
      - name: login-to-docker
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: docker build
        run: docker build -t kdale119/inventory-system .
      - name: docker publish
        run: docker push kdale119/inventory-system:latest

  deploy:
    needs: build
    runs-on: [aws-ec2-runner]
    steps:
      - name: pull-docker-img
        run: sudo docker pull kdale119/inventory-system:latest
      - name: remove-running-container
        run: sudo docker rm -f inventory-system
      - name: run-container
        run: sudo docker run -d -p 8080:8080 --name inventory-system kdale119/inventory-system:latest